stages:
  - test
  - staging
  - production

test:
  image: centos/python-36-centos7
  stage: test

  cache:
    key: $CI_PROJECT_ID-pip
    paths:
      - $CI_PROJECT_DIR/pip

  script:
    - mkdir -p $CI_PROJECT_DIR/pip
    - pip install --upgrade pip
    - pip install --cache-dir=$CI_PROJECT_DIR/pip -r requirements/dev.txt
    - pip install --cache-dir=$CI_PROJECT_DIR/pip -e .
    - make test
